
<?php $bugFiles = $this->getBugFiles() ?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-account"><?php echo $this->__('Magebugger Cache Information')?></h4>
	</div>
	<div class="fieldset">
		<table class="magebug-files-bound" ><tr><td>
			<div id="magebug-files">
		<?php if(count($bugFiles)):?>
				<table class="magebug-files" cellpadding="0" cellspacing="0" >
					<tr><th class="title"><?php echo $this->__('File Name')?></th>
					<th class="value"><?php echo $this->__('Size')?></th></tr>
			<?php foreach($bugFiles as $file): ?>
					<tr><td class="title"><?php echo $file->getName() ?></td>
					<td class="value"><?php echo $file->getSize() ?></td></tr>
			<?php endforeach; ?>
				</table>
		<?php else: ?>
			<div class="notice-msg" style="width:600px;font-weight:bold;padding:5px 20px 5px 50px;margin:0 0 10px 0;">
			    <?php echo $this->__('There are no bugs cache.') ?>
			</div>			
		<?php endif; ?>
			</div>
		</td></tr>
		<tr><td>
			<form action="<?php echo $this->getUrl('*/*/clear') ?>" method="post" >
				<button type="submit" >
					<span>Clear Magebug Cache</span>
				</button>
				<input type="hidden" name="form_key" value="<?php echo $this->getFormKey()?>" />
			</form>
		</td></tr>
		</table>
	</div>
</div>
<style>
.magebug-files-bound{
	margin:0 0 0 150px;
}
#magebug-files table.magebug-files{
	width:600px;
	margin:10px 0 10px 0;
	border-top:1px solid #7f7f7f;
	border-left:1px solid #7f7f7f;
}
.magebug-files th{
	padding:5px 20px 5px 20px;
}
.magebug-files td{
	padding:2px 20px 2px 20px;
}
.magebug-files th, .magebug-files td{
	border-bottom:1px solid #7f7f7f;
	border-right:1px solid #7f7f7f;	
}
</style>